### ISSUE TITLE
Grid disappears when detaching a plot with grid_auto_fit=False 

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#55] opened 2017-06-01 07:54 UTC
Just doing this:
```
plot = K3D(grid=[0,0,0,1,1,1], grid_auto_fit=False)
plot
```
displays a grid.

Clicking the detach button results in a window with the grid gone (white canvas, buttons still there).

Reattaching did not restore the grid display.

**Comment by tgandor** [comment] 2017-06-01 14:05
Acknowledged.

It also happens with objects on the plot - after undocking the objects are painted, but there is no grid.
It is a recent regression, and will be fixed when we finish a couple of major changes.

![k3d-1496325853598](https://cloud.githubusercontent.com/assets/11498967/26683407/f764680a-46e3-11e7-91ae-2c58dbc9d663.png)

**Comment by tgandor** [comment] 2017-06-01 14:11
I allowed myself to change the title of this issue - probably there's an unnecessary connection between grid recalculation and re-rendering.

**Comment by artur-trzesiok** [comment] 2017-06-07 19:04
After https://github.com/K3D-tools/K3D-jupyter/commit/995a03feba4c5e75be8db9c6156e63cce75c9fb8 i cannot reproduce this issue. @tgandor could you check it on latest version?

**Comment by tgandor** [comment] 2017-06-10 06:27
Checking on devel branch (version 2.1.0) - the grid is correctly redrawn both with camera_auto_fit=True and camera_auto_fit=False. Closing.

**Closed by tgandor** 2017-06-10 06:27 UTC
