### ISSUE TITLE
Streamlines example - Missing files

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#280] opened 2021-05-13 11:10 UTC
I was looking at [this streamline example](https://k3d-jupyter.org/showcase/streamlines.html) but I'm unable to find the necessary files to run it. Can they be shared?

**Comment by artur-trzesiok** [comment] 2021-05-14 05:59
Yes, this is a showscase rather than example thats why I don't put data file to github. I cannot find those file on my disk. @marcinofulus do you have it on your storage somewhere?

**Comment by Davide-sd** [comment] 2021-05-15 21:27
@artur-trzesiok I've been able to "replicate" the streamline procedure to my case, however I've encountered a problem. Let me post the code first:

```python
import numpy as np
import vtk
from vtk.util import numpy_support
import k3d
plot = k3d.plot()

def get_seeds_points(xx, yy, zz, uu, vv, ww):
    """ Select grid points on the surface of the discretized space
    where the vector is directed inside the domain.

    Parameters
    ==========
        xx, yy, zz: np.ndarray
            3D discretization of the space from meshgrid.

        uu, vv, ww: np.ndarray
            Vector components calculated at the discretized points in space.
    
    Returns
    =======
        points : np.ndarray
            [n x 3] matrix of seed-points coordinates.
    """

    # TODO: OPTIMIZE THIS CODE PLEASE!!!!!!!!!

    coords = np.stack([xx, yy, zz])
    # vector field
    vf = np.stack([uu, vv, ww])
    
    # extract the coordinate of the points at planes:
    # x_min, x_max, y_min, y_max, z_min, z_max
    c_xmin = coords[:, :, 0, :]
    c_xmax = coords[:, :, -1, :]
    c_ymin = coords[:, 0, :, :]
    c_ymax = coords[:, -1, :, :]
    c_zmin = coords[:, :, :, 0]
    c_zmax = coords[:, :, :, -1]

    # extract the vector field points at planes:
    # x_min, x_max, y_min, y_max, z_min, z_max
    vf_xmin = vf[:, :, 0, :]
    vf_xmax = vf[:, :, -1, :]
    vf_ymin = vf[:, 0, :, :]
    vf_ymax = vf[:, -1, :, :]
    vf_zmin = vf[:, :, :, 0]
    vf_zmax = vf[:, :, :, -1]
    
    def find_points_at_input_vectors(vf_plane, coords, i, sign="g"):
        check = {
            "g": lambda x: x > 0,
            "l": lambda x: x < 0,
        }
        # extract coordinates where the vectors are entering the plane
        tmp = np.where(check[sign](vf_plane[i, :, :]), coords, np.nan * np.zeros_like(coords))
        # reshape the matrix to obtain an [n x 3] array of coordinates
        tmp = np.array([tmp[0, :, :].flatten(), tmp[1, :, :].flatten(), tmp[2, :, :].flatten()]).T
        # remove NaN entries
        tmp = [a for a in tmp if not np.all([np.isnan(t) for t in a])]
        return tmp
    
    p_xmin = find_points_at_input_vectors(vf_xmin, c_xmin, 0, "g")
    p_xmax = find_points_at_input_vectors(vf_xmax, c_xmax, 0, "l")
    p_ymin = find_points_at_input_vectors(vf_ymin, c_ymin, 1, "g")
    p_ymax = find_points_at_input_vectors(vf_ymax, c_ymax, 1, "l")
    p_zmin = find_points_at_input_vectors(vf_zmin, c_zmin, 2, "g")
    p_zmax = find_points_at_input_vectors(vf_zmax, c_zmax, 2, "l")
    # TODO: there could be duplicates
    points = np.array(p_xmin + p_xmax + p_ymin + p_ymax + p_zmin + p_zmax)
    return points

n1, n2, n3 = 10, 10, 10
x = np.linspace(-10, 10, n1)
y = np.linspace(-8, 8, n2)
z = np.linspace(-6, 6, n3)
xx, yy, zz = np.meshgrid(x, y, z)
uu, vv, ww = zz, yy, xx
magnitude = np.sqrt(uu**2 + vv**2 + ww**2)
min_mag = min(magnitude.flatten())
max_mag = max(magnitude.flatten())

vector_field = np.array([uu.flatten(), vv.flatten(), ww.flatten()]).T
vtk_vector_field = numpy_support.numpy_to_vtk(num_array=vector_field, deep=True, array_type=vtk.VTK_FLOAT)
vtk_vector_field.SetName("vector_field")

points = vtk.vtkPoints()
points.SetNumberOfPoints(n2 * n1 * n3)
for i, (x, y, z) in enumerate(zip(xx.flatten(), yy.flatten(), zz.flatten())):
    points.SetPoint(i, [x, y, z])
grid = vtk.vtkStructuredGrid()
grid.SetDimensions([n2, n1, n3])
grid.SetPoints(points)
grid.GetPointData().SetVectors( vtk_vector_field )

seeds_points = get_seeds_points(xx, yy, zz, uu, vv, ww)
plt_points = k3d.points(positions=seeds_points.astype(np.float32), point_size=0.2)
plot += plt_points
seeds = vtk.vtkPolyData()
points = vtk.vtkPoints()
for p in seeds_points:
    points.InsertNextPoint(p)
seeds.SetPoints(points)

streamer = vtk.vtkStreamTracer()
streamer.SetInputData(grid)
streamer.SetSourceData(seeds)
streamer.SetMaximumPropagation(500)
streamer.SetIntegrationDirectionToForward()
streamer.SetComputeVorticity(0)
streamer.SetIntegrator(vtk.vtkRungeKutta4())
streamer.Update()

streamline = streamer.GetOutput()
streamlines_points = numpy_support.vtk_to_numpy(streamline.GetPoints().GetData())
streamlines_velocity = numpy_support.vtk_to_numpy(streamline.GetPointData().GetArray('vector_field'))
streamlines_speed = np.linalg.norm(streamlines_velocity, axis=1)

vtkLines = streamline.GetLines()
vtkLines.InitTraversal()
point_list = vtk.vtkIdList()

lines = []
lines_attributes = []

while vtkLines.GetNextCell(point_list):
    start_id = point_list.GetId(0)
    end_id = point_list.GetId(point_list.GetNumberOfIds() - 1)
    l= []
    v= []

    for i in range(start_id, end_id):
        l.append(streamlines_points[i])
        v.append(streamlines_speed[i])

    lines.append(np.array(l))
    lines_attributes.append(np.array(v))

cm = k3d.matplotlib_color_maps.Inferno
for l, a in zip(lines, lines_attributes):
    if len(l) >= 3:
        plot += k3d.line(l, attribute=a, width=0.1,
                    color_map=cm, color_range=[min_mag, max_mag])

plot.display()
```

In this case, a little more than 80 streamlines will be added to the plot. However, the rendering is slow, even though the number of overall points is low. I think that adding that many objects is causing JS to slow down quite a lot.

Is there any way to "group" the lines together maybe into a mesh (keeping the attribute to apply the colormap), in order to speed up the rendering?

**Comment by tgandor** [comment] 2021-05-17 17:44
IIRC, there was a "NaN-hack" to plot multiple lines as a single line (by having 1 (NaN, NaN, NaN) vertex between "separate lines"). I don't know if it still works, and if it works for all renderers, but this brings down the number of objects and probably speeds things up a little bit.

**Comment by Davide-sd** [comment] 2021-05-17 20:15
> IIRC, there was a "NaN-hack" to plot multiple lines as a single line (by having 1 (NaN, NaN, NaN) vertex between "separate lines")

I think that hack doesn't work anymore:

```python
import numpy as np
import vtk
from vtk.util import numpy_support
import k3d
plot = k3d.plot()

def get_seeds_points(xx, yy, zz, uu, vv, ww):
    """ Select grid points on the surface of the discretized space
    where the vector is directed inside the domain.

    Parameters
    ==========
        xx, yy, zz: np.ndarray
            3D discretization of the space from meshgrid.

        uu, vv, ww: np.ndarray
            Vector components calculated at the discretized points in space.
    
    Returns
    =======
        points : np.ndarray
            [n x 3] matrix of seed-points coordinates.
    """

    # TODO: OPTIMIZE THIS CODE PLEASE!!!!!!!!!

    coords = np.stack([xx, yy, zz])
    # vector field
    vf = np.stack([uu, vv, ww])
    
    # extract the coordinate of the points at planes:
    # x_min, x_max, y_min, y_max, z_min, z_max
    c_xmin = coords[:, :, 0, :]
    c_xmax = coords[:, :, -1, :]
    c_ymin = coords[:, 0, :, :]
    c_ymax = coords[:, -1, :, :]
    c_zmin = coords[:, :, :, 0]
    c_zmax = coords[:, :, :, -1]

    # extract the vector field points at planes:
    # x_min, x_max, y_min, y_max, z_min, z_max
    vf_xmin = vf[:, :, 0, :]
    vf_xmax = vf[:, :, -1, :]
    vf_ymin = vf[:, 0, :, :]
    vf_ymax = vf[:, -1, :, :]
    vf_zmin = vf[:, :, :, 0]
    vf_zmax = vf[:, :, :, -1]
    
    def find_points_at_input_vectors(vf_plane, coords, i, sign="g"):
        check = {
            "g": lambda x: x > 0,
            "l": lambda x: x < 0,
        }
        # extract coordinates where the vectors are entering the plane
        tmp = np.where(check[sign](vf_plane[i, :, :]), coords, np.nan * np.zeros_like(coords))
        # reshape the matrix to obtain an [n x 3] array of coordinates
        tmp = np.array([tmp[0, :, :].flatten(), tmp[1, :, :].flatten(), tmp[2, :, :].flatten()]).T
        # remove NaN entries
        tmp = [a for a in tmp if not np.all([np.isnan(t) for t in a])]
        return tmp
    
    p_xmin = find_points_at_input_vectors(vf_xmin, c_xmin, 0, "g")
    p_xmax = find_points_at_input_vectors(vf_xmax, c_xmax, 0, "l")
    p_ymin = find_points_at_input_vectors(vf_ymin, c_ymin, 1, "g")
    p_ymax = find_points_at_input_vectors(vf_ymax, c_ymax, 1, "l")
    p_zmin = find_points_at_input_vectors(vf_zmin, c_zmin, 2, "g")
    p_zmax = find_points_at_input_vectors(vf_zmax, c_zmax, 2, "l")
    # TODO: there could be duplicates
    points = np.array(p_xmin + p_xmax + p_ymin + p_ymax + p_zmin + p_zmax)
    return points

n1, n2, n3 = 10, 10, 10
x = np.linspace(-10, 10, n1)
y = np.linspace(-8, 8, n2)
z = np.linspace(-6, 6, n3)
xx, yy, zz = np.meshgrid(x, y, z)
uu, vv, ww = zz, yy, xx
magnitude = np.sqrt(uu**2 + vv**2 + ww**2)
min_mag = min(magnitude.flatten())
max_mag = max(magnitude.flatten())

vector_field = np.array([uu.flatten(), vv.flatten(), ww.flatten()]).T
vtk_vector_field = numpy_support.numpy_to_vtk(num_array=vector_field, deep=True, array_type=vtk.VTK_FLOAT)
vtk_vector_field.SetName("vector_field")

points = vtk.vtkPoints()
points.SetNumberOfPoints(n2 * n1 * n3)
for i, (x, y, z) in enumerate(zip(xx.flatten(), yy.flatten(), zz.flatten())):
    points.SetPoint(i, [x, y, z])
grid = vtk.vtkStructuredGrid()
grid.SetDimensions([n2, n1, n3])
grid.SetPoints(points)
grid.GetPointData().SetVectors( vtk_vector_field )

seeds_points = get_seeds_points(xx, yy, zz, uu, vv, ww)
plt_points = k3d.points(positions=seeds_points.astype(np.float32), point_size=0.2)
plot += plt_points
seeds = vtk.vtkPolyData()
points = vtk.vtkPoints()
for p in seeds_points:
    points.InsertNextPoint(p)
seeds.SetPoints(points)

streamer = vtk.vtkStreamTracer()
streamer.SetInputData(grid)
streamer.SetSourceData(seeds)
streamer.SetMaximumPropagation(5000)
streamer.SetIntegrationDirectionToForward()
streamer.SetComputeVorticity(0)
streamer.SetIntegrator(vtk.vtkRungeKutta4())
streamer.Update()

streamline = streamer.GetOutput()
streamlines_points = numpy_support.vtk_to_numpy(streamline.GetPoints().GetData())
streamlines_velocity = numpy_support.vtk_to_numpy(streamline.GetPointData().GetArray('vector_field'))
streamlines_speed = np.linalg.norm(streamlines_velocity, axis=1)

vtkLines = streamline.GetLines()
vtkLines.InitTraversal()
point_list = vtk.vtkIdList()

lines = []
lines_attributes = []

while vtkLines.GetNextCell(point_list):
    start_id = point_list.GetId(0)
    end_id = point_list.GetId(point_list.GetNumberOfIds() - 1)
    l= []
    v= []

    for i in range(start_id, end_id):
        l.append(streamlines_points[i])
        v.append(streamlines_speed[i])

    lines.append(np.array(l))
    lines_attributes.append(np.array(v))

cm = k3d.matplotlib_color_maps.Inferno
count = sum([len(l) for l in lines])
vertices = np.zeros((count + (len(lines) - 1), 3), dtype=np.float32)
attributes = np.zeros(count + (len(lines) - 1), dtype=np.float32)
c = 0
for k, (l, a) in enumerate(zip(lines, lines_attributes)):
    vertices[c : c + len(l), :] = l.astype(np.float32)
    attributes[c : c + len(l)] = a.astype(np.float32)
    if k < len(lines) - 1:
        vertices[c + len(l) + 1, :] = np.nan * np.zeros(3)
        attributes[c + len(l) + 1] = np.nan
        c = c + len(l) + 1
plot +=k3d.line(
    vertices,
    attribute=attributes, width=0.1, shader="mesh")

plot.display()
```
![K3D-1621281325061](https://user-images.githubusercontent.com/9921777/118550200-abac4480-b75c-11eb-97ec-063268d53107.png)

By looking at the vertices with `plot.objects[1].vertices[:30, :]`, it seems like NaN gets converted to zero.

```
array([[-10.        ,  -6.2222223 ,   6.        ],
       [ -9.341722  ,  -7.028082  ,   4.823669  ],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -4.4444447 ,   2.        ],
       [ -9.816059  ,  -5.1223392 ,   0.59584886],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -4.4444447 ,   3.3333333 ],
       [ -9.629946  ,  -5.112378  ,   1.9613788 ],
       [ -9.447836  ,  -5.8915343 ,   0.61053455],
       [ -9.453612  ,  -6.765197  ,  -0.6941826 ],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -4.4444447 ,   4.6666665 ],
       [ -9.45544   ,  -5.092763  ,   3.3441246 ],
       [ -9.074987  ,  -5.8682895 ,   2.0330398 ],
       [ -8.8768635 ,  -6.764628  ,   0.75931025],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -4.4444447 ,   6.        ],
       [ -9.298542  ,  -5.0655956 ,   4.739506  ],
       [ -8.727141  ,  -5.8217573 ,   3.48756   ],
       [ -8.315098  ,  -6.7197013 ,   2.2673671 ],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -2.6666667 ,   2.        ],
       [ -9.810894  ,  -3.1024005 ,   0.5036929 ],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -2.6666667 ,   3.3333333 ],
       [ -9.612432  ,  -3.0955682 ,   1.8735113 ],
       [ -9.436657  ,  -3.6137934 ,   0.40217373],
       [ -9.486129  ,  -4.2135606 ,  -1.0477732 ],
       [  0.        ,   0.        ,   0.        ],
       [-10.        ,  -2.6666667 ,   4.6666665 ]], dtype=float32)
```

**Comment by artur-trzesiok** [comment] 2021-05-17 23:57
The hack works but only for shader='simple'. 
Can you create snapshot from your version and share here? I will analyse why it is slow.

**Comment by artur-trzesiok** [comment] 2021-05-18 01:05
Btw I can add nan-hack support to shader='mesh'. Still please consider that as unofficial one ;)

**Comment by Davide-sd** [comment] 2021-05-18 08:52
> Can you create snapshot from your version and share here? I will analyse why it is slow.

What do you mean with snapshot? I shared my code in the previous comment...

> Without snapshot is hard to guess but I think this is not a problem with slow rendering but with rendering after every objects. Please set plot.auto_rendering = False before adding objects to scene and after all objects will be added use
plot.auto_rendering = True

I tried to set `plot.auto_rendering` but the difference is really minimal, still extremely slow.

Please, would you try to run the code I've posted in the previous comment to see if it works with you?

**Comment by Davide-sd** [comment] 2021-05-18 09:11
Ok, problem solved. In the above example I initialized `vertices` with `dtype=np.float32`, but `np.nan` is a float64. Apparently, Numpy convert `np.nan` to zero in float32.

I'm pasting the edits to my previous code:
```
vertices = np.nan * np.zeros((count + (len(lines) - 1), 3))
attributes = np.zeros(count + (len(lines) - 1))
c = 0
for k, (l, a) in enumerate(zip(lines, lines_attributes)):
    vertices[c : c + len(l), :] = l
    attributes[c : c + len(l)] = a
    if k < len(lines) - 1:
        c = c + len(l) + 1

plot +=k3d.line(
    vertices.astype(np.float32),
    attribute=attributes, width=0.1, shader="mesh")
```

Everything works fine. The NaN hack works with all shaders.

Thank you for your patience. I think this issue can be closed.

**Comment by tgandor** [comment] 2021-05-18 13:38
Thanks for your feedback, @Davide-sd!

I wanted to test this myself, because I was uneasy about these zeros in array, but I had problems building my K3D locally.

This is such a WAT with this float32 vs float64 NaN! Why is NumPy doing such things to us? I don't know.

I'm happy you found a way around it, and to know we have a new hacker-level user of K3D. Closing issue.

**Comment by artur-trzesiok** [comment] 2021-05-18 14:15
I would like to reopen this issue because here is a lot of potential value under the hood.

Frist of all - congratulations about spotting that behavior of numpy with cast nan to 0 (that is strange!). I would like to also explain what is a snapshot in k3d:
![image](https://user-images.githubusercontent.com/5256837/118664563-88e96100-b82c-11eb-81c0-e84bacf18af4.png)

That produce a standalone version of current state of widget in html. That snapshot in our cases will be usefull to pass to me your state of k3d to reproduce low performance. I ask about that because by my mistake I assumed that your code require external velocity field - sorry for that.

I was confused as to why displaying 600 objects slows down K3D so much and discovered where the problem was. The reason of all is...the menu on the upper right (!?). 

Please check your first code in this issue with:

`plot = k3d.plot(menu_visibility = True)`

That is sooo strange. I will try to ask somebody from dat.gui how to solve that.

**Comment by artur-trzesiok** [comment] 2021-05-18 14:32
btw. @marcinofulus commited missing files: https://github.com/K3D-tools/K3D-jupyter/commit/2009fee05d0dce38f257a764004c15a0b6913fa0

**Comment by Davide-sd** [comment] 2021-05-18 15:11
> I was confused why displaying 600 objects slows down K3D so much and discovered where the problem is located. The reason of all is...the menu on the upper right (!?). Please check your first code in this issue with: `plot = k3d.plot(menu_visibility = False)`

I tried your suggestion with the first code I posted, I see no difference at all. It is always slow.

**Comment by artur-trzesiok** [comment] 2021-05-18 15:12
@Davide-sd what version of k3d do you use? Please try on 2.9.5+

**Comment by Davide-sd** [comment] 2021-05-18 16:18
Ok, I installed the latest with `pip install git+https://github.com/K3D-tools/K3D-jupyter` and there is indeed a considerable performance difference.

**Closed** 2021-05-24 01:49 UTC
