### ISSUE TITLE
Setting up a development version

### ISSUE THREAD

**Issue by Davide-sd** [K3D-tools/K3D-jupyter#281] opened 2021-05-15 11:48 UTC
I'm having troubles setting up a development version for K3D.

These are the steps I tried:
* cd into my `/home/davide/Documents/Development` folder.
* `virtualenv k3ddev`
* `source k3ddev/bin/activate`
* `pip install ipython notebook`
* some command to add the environment to the jupyter notebook kernel list.
*  `git clone https://github.com/K3D-tools/K3D-jupyter`
* modified a few files into K3D-Jupyter (both Python and JS files).
* `cd K3D-jupyter` and `pip install -e . --no-cache-dir`
* `jupyter notebook`
* Opened a new notebook with my `k3ddev` environment.
```
import k3d
help(k3d.plot)
```
At this point, none of my edits are visible. The docstring and the code seems like unaffected by my edits. It's like I haven't modified the files at all... If I try:
```
k3d.__path__
```
I get: `['/home/davide/Documents/Development/K3D-jupyter/k3d']`... 

Why are my edits not included in the installed package?

**Comment by artur-trzesiok** [comment] 2021-05-17 01:15
Hi!

First of all - all features from devel are merged into master so you can simply install k3d@2.9.5. About managing virtualenv in python ecosystem I'm not a master. @tgandor or @marcinofulus  - you have stronger experience with that, maybe you see straightforward hint?

**Comment by tgandor** [comment] 2021-05-17 17:32
Hi again, @Davide-sd - well, as you already mentioned in https://github.com/K3D-tools/K3D-jupyter/issues/281 - we would benefit greatly from a good "Installation" section in the documentation :)

The problem is - there are "too many ways to do it" - jupyter in site-packages system-wide, jupyter in user directory, inside virtualenv, inside conda env, K3D from conda-forge, K3D from PyPI, K3D from sources...
Almost all the permutations can be made to work, but often troubleshooting is impossible without physically going into the shell and diagnosing what's going on. Or go the "IT Crowd" way - remove everything and reinstall new version from scratch (together with jupyter, ipywidgets, etc...).

This led some of us to have "helper scripts" like this: https://github.com/tgandor/meats/blob/master/installer/k3d_notebook.sh.bat

About this specific issue: I'll try to reproduce it. `pip -e .` used to work great for me, I'm surprised there are issues. I would check if there's nothing funny going on with .pyc files, or module reloading, or the kernel having the old version loaded. I'll get back to you if I find something.

**Closed** 2021-07-08 20:57 UTC
